# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ae7783b99c52ec1480af56ab1f7b33682edbfd54395cad13dd6a1d3e23ef8fc62acf7d493c681160fbd4cc3a2990b965d4929a8d14944891a9e08832f2b4792

test:
  secret_key_base: 13a4dc44f14ae5371d6c424f010161085eb38e19a496c8629cf88609b404654d8d3afd6afce7d131a62f18ccfacd26fde5e33a3b4fb884b654b715f1be76cf58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
